### ISSUE TITLE
no response after clicking calculate button

### ISSUE THREAD

**Issue by kumar-pintlab** [Manojk-1989/interview-template-angular-and-laravel#1]
![image](https://user-images.githubusercontent.com/28713687/204284320-c1fe042c-d9c3-4e09-826d-fb6a97263773.png)

**Request Details**

![image](https://user-images.githubusercontent.com/28713687/204284411-fdaf84c7-a47e-4098-b5b8-1593d819ac30.png)

![image](https://user-images.githubusercontent.com/28713687/204284462-8eec9170-850e-46a8-852c-424cfa43aa4d.png)

**Response**

![image](https://user-images.githubusercontent.com/28713687/204284535-51524914-17b7-4bc4-95bd-d10d2e2b58b0.png)

**Comment by Manojk-1989** [comment]
you need to do following steps to run this project
"go to -> project folder  -> back-end" then execute the following comands
1 =>  php artisan vendor:publish
--provider="Tymon\JWTAuth\Providers\LaravelServiceProvider" 2 =>  php
artisan jwt:secret
